services:
  frontend:
    build:
      context: ./dash/
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - database_default
    ports:
      - "8050:8050"
    restart: always

networks:
  database_default:
    external: true