services:

  database:
    image: postgres
    container_name: iotfinal_postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - "9100:9100"
    networks:
      - backend_default
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    
networks:
  backend_default:
    external: true