services:

  database:
    image: postgres
    container_name: iotfinal
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    
networks:
  default:
    ipam:
      config:
        - subnet: 172.19.1.0/24