create database postgres
    with owner root;

comment on database postgres is 'default administrative connection database';

create sequence public.predictions_id_seq
    as integer;

alter sequence public.predictions_id_seq owner to root;

create table public.temperature
(
    id        bigint generated by default as identity
        primary key,
    value     double precision,
    timestamp timestamp
);

alter table public.temperature
    owner to root;

create table public.humidity
(
    id        bigint generated by default as identity
        primary key,
    value     double precision,
    timestamp timestamp
);

alter table public.humidity
    owner to root;

create table public.humidity_dummy
(
    id        bigserial
        constraint humidity_dummy_pk
            primary key,
    value     double precision,
    timestamp timestamp
);

alter table public.humidity_dummy
    owner to root;

create table public.temperature_dummy
(
    id        bigserial
        constraint temperature_dummy_pk
            primary key,
    value     double precision,
    timestamp timestamp
);

alter table public.temperature_dummy
    owner to root;

create table public.prediction
(
    id          bigint default nextval('predictions_id_seq'::regclass) not null
        constraint prediction_pk
            primary key,
    temperature integer,
    humidity    double precision,
    timestamp   timestamp
);

alter table public.prediction
    owner to root;

alter sequence public.predictions_id_seq owned by public.prediction.id;

create table public.model_accuracy
(
    id        bigint generated by default as identity
        constraint model_accuracy_pk
            primary key,
    mae       double precision not null,
    mape      double precision not null,
    mse       double precision not null,
    rmse      double precision not null,
    timestamp timestamp        not null,
    model     varchar          not null
);

alter table public.model_accuracy
    owner to root;

